-- ============================================================
-- HAMBURGUESA DE BARRIO — esquema de la base de datos
-- ============================================================
-- Pegar y ejecutar este archivo entero en Supabase:
-- tu proyecto → SQL Editor → New query → pegar → Run

create table public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  customer_name text not null,
  phone text not null,
  order_type text not null check (order_type in ('retiro','delivery')),
  address text,
  payment_method text not null check (payment_method in ('efectivo','mercado_pago')),
  items jsonb not null,
  notes text,
  total numeric not null,
  status text not null default 'pendiente'
    check (status in ('pendiente','aceptado','rechazado','listo','entregado'))
);

-- Activar seguridad a nivel de fila (RLS)
alter table public.orders enable row level security;

-- Cualquiera puede CREAR un pedido (son los clientes desde la web pública),
-- pero solo puede crearlo con estado "pendiente" — no puede marcarlo como
-- aceptado, listo, etc. desde afuera.
create policy "clientes pueden crear pedidos"
on public.orders
for insert
to anon
with check (status = 'pendiente');

-- Solo usuarios logueados (el local) pueden VER los pedidos.
create policy "empleados pueden ver pedidos"
on public.orders
for select
to authenticated
using (true);

-- Solo usuarios logueados (el local) pueden ACTUALIZAR el estado.
create policy "empleados pueden actualizar pedidos"
on public.orders
for update
to authenticated
using (true)
with check (true);

-- Habilitar actualizaciones en tiempo real para esta tabla
-- (para que el panel de empleados vea los pedidos nuevos sin refrescar)
alter publication supabase_realtime add table public.orders;
